### ISSUE TITLE
Merge with `davda54/sam`

### ISSUE THREAD

**Issue by davda54** [juntang-zhuang/GSAM#7]
Hi, thank you very much for your great work! I'd be happy to incorporate your SAM variant into my repository at [https://github.com/davda54/sam](https://github.com/davda54/sam). Are you okay with directly adding the functionality into the code in my repo? Or would you prefer if I only link this repository from the main readme file?

**Comment by juntang-zhuang** [comment]
Sure, adding into the code is good to me. Thanks for your effect with the original SAM pytorch implementation!

**Comment by davda54** [comment]
Thanks a lot! Could you have a quick look to [this pull request](https://github.com/davda54/sam/pull/72/files)? Is there anything obvious missing/incorrect?

**Comment by juntang-zhuang** [comment]
LGTM
